name: Release

on: 
  release:
    types:
      - published

jobs:
  release:
    name: Publish GitHub and Cocoapods release
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_15.2.app

      - name: Build
        run: |
          swift build -c release --arch arm64 --arch x86_64
          cp ./.build/apple/Products/Release/figma-export ./Release/figma-export
          cp -r ./.build/apple/Products/Release/figma-export_AndroidExport.bundle ./Release/figma-export_AndroidExport.bundle
          cp -r ./.build/apple/Products/Release/figma-export_XcodeExport.bundle ./Release/figma-export_XcodeExport.bundle
          zip -r figma-export.zip Release LICENSE

      - name: "Upload assets to a release"
        run: gh release upload ${{ github.event.release.tag_name }} figma-export.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push FigmaExport.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

      - name: Update Homebrew formulae
        run: gh workflow run bump-formula.yml --repo RedMadRobot/homebrew-formulae --field formula=figma-export --field version=${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
